declare const enum CharacterEventType {
    PickUp = 'PickUp',
    Drop = 'Drop',
    GrabProp = 'GrabProp',
    UnGrabProp = 'UnGrabProp',
    EnterVehicle = 'EnterVehicle',
    LeaveVehicle = 'LeaveVehicle',
    Respawn = 'Respawn',
    Death = 'Death',
    TakeDamage = 'TakeDamage',
    Fire = 'Fire',
    Possessed = 'Possessed',
    UnPossessed = 'UnPossessed',
    Punch = 'Punch',
    WeaponAimModeChanged = 'WeaponAimModeChanged',
    ViewModeChanged = 'ViewModeChanged',
    SwimmingModeChanged = 'SwimmingModeChanged',
    StanceModeChanged = 'StanceModeChanged',
    RagdollModeChanged = 'RagdollModeChanged',
    FallingModeChanged = 'FallingModeChanged',
    GaitModeChanged = 'GaitModeChanged'
}